//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobApplications.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class employment_agency_contact
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public employment_agency_contact()
        {
            this.job_applications = new HashSet<job_application>();
        }
    
        public int id { get; set; }
        public Nullable<int> employment_agency_id { get; set; }
        public string contact_name { get; set; }
        public string contact_email { get; set; }
        public string contact_telephone { get; set; }
        public System.DateTime last_updated { get; set; }
    
        public virtual employment_agency employment_agency { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<job_application> job_applications { get; set; }
    }
}
