//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobApplications.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class employment_agency
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public employment_agency()
        {
            this.job_applications = new HashSet<job_application>();
            this.employment_agency_contacts = new HashSet<employment_agency_contact>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string url { get; set; }
        public Nullable<System.DateTime> last_updated { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<job_application> job_applications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<employment_agency_contact> employment_agency_contacts { get; set; }
    }
}
