//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobApplications.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class job_application
    {
        public int id { get; set; }
        public Nullable<int> job_site_id { get; set; }
        public string job_site_reference { get; set; }
        public Nullable<int> employment_agency_id { get; set; }
        public Nullable<int> employment_agency_contact_id { get; set; }
        public string employment_agency_reference { get; set; }
        public string company_name { get; set; }
        public string company_location { get; set; }
        public string job_title { get; set; }
        public Nullable<System.DateTime> application_date { get; set; }
        public System.DateTime last_updated { get; set; }
    
        public virtual employment_agency employment_agency { get; set; }
        public virtual employment_agency_contact employment_agency_contact { get; set; }
        public virtual job_site job_site { get; set; }
    }
}
