//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobApplications.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class job_searchEntities : DbContext
    {
        public job_searchEntities()
            : base("name=job_searchEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<employment_agency> employment_agencies { get; set; }
        public virtual DbSet<employment_agency_contact> employment_agency_contacts { get; set; }
        public virtual DbSet<job_application> job_applications { get; set; }
        public virtual DbSet<job_site> job_sites { get; set; }
    }
}
